version: '2'

services:

  # Universal Automation
  app:
    restart: always
    build:
      context: app/
    env_file: app/.env
    volumes:
      - app_database:C:\App\Database
    ports:
      - "8080:8080"
      - "10000:10000"

volumes:
  app_database:
